### ISSUE TITLE
Oracle integration test. Bucket names is fix.

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/binary-builder#18]
Hi,

I am forking the PHP buildpack to add the PHP support and binary.
I am reusing some of the integration test into my ConcourseCI pipeline, the fact is the bucket name is fix https://github.com/cloudfoundry/binary-builder/blob/04cc30b41b21d02e0f9abcd90bcd1037bb1d6b52/spec/spec_helper.rb#L51

So I would like to avoid to fork the binary builder just to use my own bucket.

Thanks

**Comment by RochesterinNYC** [comment]
@shinji62 are you running the binary builder integration tests locally or via the associated [script](https://github.com/cloudfoundry/buildpacks-ci/blob/master/scripts/binary-builder-integration.sh) ? The code involving the oracle tests should not execute unless this tag is specified: `--tag ~run_oracle_php_tests`

**Comment by shinji62** [comment]
Running with Concourse and my custom / fork  buildpack include Oracle too.
As long as I fork the binary-builder repos I would like to be able to test it, including oracle.

**Comment by sesmith177** [comment]
Hello @shinji62,

We agree that being able to configure the bucket containing the Oracle libs would be useful. We will turn the [bug](https://www.pivotaltracker.com/story/show/129911999) into a feature story and prioritize as appropriate.

**Comment by sclevine** [comment]
Feature story here: https://www.pivotaltracker.com/story/show/130240605

**Comment by shinji62** [comment]
Nice guys ! thanks

**Comment by sesmith177** [comment]
@shinji62 This has been implemented as of [this commit](https://github.com/cloudfoundry/buildpacks-ci/commit/e7f923258e9c10c2cfee7bf2f29dd075b68c9973) on buildpacks-ci on buildpacks-ci and commit 777dde69e4be7af086efb2a64a3d8393d8421f2b on binary-builder.
