### ISSUE TITLE
How to check if a built binary runs correctly on CF?

### ISSUE THREAD

**Issue by mweibel** [cloudfoundry/binary-builder#19]
I'm adding [a new extension in my fork](https://github.com/cloudfoundry/binary-builder/compare/master...mweibel:feature/kafka-extension?expand=1) and before sending you a PR I'd like to test if it actually works ;) 
Do I need to launch an own Cloud Foundry instance where I can push that new buildpack and then try it or is there a possibility to use such a buildpack as a non-admin in an existing CF instance?

**Comment by sclevine** [comment]
Hi @mweibel,

The `-b` flag for the `cf push` command allows you to specify a URL to an arbitrary buildpack git repo or zip file. Run `cf help push` for more details. Buildpack code has no special privileges compared to app code in CF, so most CF installations are configured to allow apps to specify arbitrary buildpacks.

(By the way, [PCF Dev](https://github.com/pivotal-cf/pcfdev) is a very quick way to spin up a whole CF install in a local VM for testing.)

**Comment by mweibel** [comment]
Hi @sclevine 
Thanks! Will try that :)
