### ISSUE TITLE
not able to edit http-module.conf

### ISSUE THREAD

**Issue by gcccoder** [cloudfoundry/binary-builder#21]
I am trying to upload a php webapp on IBM bluemix . I want to use few commented modules (specially auto_index module) to enable using methods like 'IdexIgnore' in .htaccess file in the root folder. How to upload the app with edited http-modules.conf file?

Thank you

**Comment by dmikusa-pivotal** [comment]
I think you're in the wrong place.  What you're trying to do can be accomplished with the PHP build pack.  Check out the docs:  https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations.  If you have questions about the docs, ask there.

**Comment by sesmith177** [comment]
Thanks @dmikusa-pivotal. Closing.
