### ISSUE TITLE
binary builder should check authenticity and integrity of downloaded packages

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/binary-builder#4]
Thanks for sharing this great work for building buildpack binaries!

As discussed into https://github.com/cloudfoundry/java-buildpack-dependency-builder/issues/6 the buildpacks binary builder should strive to verify authenticiy and integrity of downloaded artefacts

For example in https://github.com/cloudfoundry/binary-builder/blob/master/templates/httpd_blueprint.sh.erb#L8-L9 the builder is currently vulnerable to man in the midddle attacks that could return compromised packages.

In the case of apache, apache source packages are digitally signed with apache public keys, and should be checked by the binary builder.

Other cases might check against checksum downloaded through HTTPS on the main distrib (and not mirror).
http://apache.mirrors.tds.net/apr/#sig

**Comment by mhoran** [comment]
Hey @gberche-orange. Thanks for bringing this to our attention. I think we should definitely download sources via HTTPS at all times, and figure out a non-intrusive way to verify signatures.

We had started this project off by downloading sources via git, in particular GitHub, and relied on the intrinsic "security" provided by the git protocol. However, we should probably spend some time improving this mechanism, as one of the major reasons behind this effort is to ensure we're confident in the integrity of our packages.

I'm wondering if the preferred mechanism would be to provide a hash of the download file to the binary builder at run time -- e.g. `./bin/binary-builder httpd <version> <hash>`, or if we should bake in the hash verification to the binary builder itself.

Fetching the hashes from the distribution sites seems like it still leaves open a man-in-the-middle attack, though if we move to all HTTPS URLs that would be more difficult -- but as history has shown, not impossible.

I'd love to hear your thoughts, and will discuss with the team tomorrow.

**Comment by gberche-orange** [comment]
I understand that fetching the source distrib checksum from the distribution through https is the standard way to check packages as they come released without including manual operation each time. I'd rather then have the binary builder do the v
download and verification itself.

As for signatures, since they typically don't change much and in particular not with each new package version it seems better to embed them into the binary builder repo I would think.


(Sorry for late response, was out if office for a while)

**Comment by flavorjones** [comment]
Thanks for pointing this out. I'm going to schedule work on making sure we're specifying the expected checksum for any downloads.

**Comment by gberche-orange** [comment]
Thanks @flavorjones 

Do you mean "making sure we're verifying the expected checksum for any downloads, against checksum securely downloaded from source repos" and verifying signature for digitally signed source packages ?

**Comment by flavorjones** [comment]
I believe we've completed the work you described above -- all the builder pipelines now require a checksum or a GPG key, see https://github.com/cloudfoundry/binary-builder/blob/master/bin/binary-builder#L34-L40.

**Comment by flavorjones** [comment]
And, to your point above, all the pipelines then use that checksum or GPG key to verify the source tarball.

If you see anything we're not doing, please do let me know. I'm putting together a track of work related to this and to your request at #5 to provide more structured metadata around a "chain of custody" so that end users of a buildpack can verify all the binaries being delivered.

**Comment by gberche-orange** [comment]
Thanks @flavorjones !

I see the source files are indeed downloaded and verified against checksum or signature [upfront](https://github.com/cloudfoundry/binary-builder/blob/1430d38656be7e2b48d02e0b3b2bfcf52649b109/templates/base.sh.erb#L29) but then the some template steps don't seem to use the downloaded and extracted tar (e.g. [httpd-apr](https://github.com/cloudfoundry/binary-builder/blob/1430d38656be7e2b48d02e0b3b2bfcf52649b109/templates/httpd_blueprint.sh.erb#L9) [jruby](https://github.com/cloudfoundry/binary-builder/blob/1430d38656be7e2b48d02e0b3b2bfcf52649b109/templates/jruby_blueprint.sh.erb#L11) ) and are therefore still vulnerable to man in the middle attacks.

Is that something you plan on fixing ?

**Comment by flavorjones** [comment]
Heya @gberche-orange,

Thanks for pointing this out. In the `jruby` case we do verify a checksum:

> https://github.com/cloudfoundry/binary-builder/blob/1430d38656be7e2b48d02e0b3b2bfcf52649b109/templates/jruby_blueprint.sh.erb#L12

but in the `httpd` case we're not. I've filed a bug report:

> https://www.pivotaltracker.com/story/show/103622774

Also worth noting that we're not yet verifying checksums when we build some dependencies in the `php-buildpack`, which I've filed another bug for here:

> https://www.pivotaltracker.com/story/show/103623654

**Comment by gberche-orange** [comment]
Thanks @flavorjones for sharing the additional stories added.

> Thanks for pointing this out. In the jruby case we do verify a checksum:

Sorry, I had missed that, thanks for correcting me on this.

**Comment by flavorjones** [comment]
Just an update that the current code on `master` verifies checksums for all the components of `httpd`.

The PHP story is in motion, and nearly done.

**Comment by flavorjones** [comment]
@gberche-orange The code for verifying checksums is here: https://github.com/cloudfoundry/binary-builder/blob/master/recipe/httpd_meal.rb#L152-L171

**Comment by gberche-orange** [comment]
@flavorjones great thanks for the update, looks good  to me.
