### ISSUE TITLE
Building PHP 7.2.16 - libargon not found

### ISSUE THREAD

**Issue by crypticro** [cloudfoundry/binary-builder#47]
I have tried to re-run the building script for PHP with oracle support for the new cflinuxfs3.

The compilation of php 7.2.16 works fine but when deploying the app using that custom buildpack it fails:

```
 /tmp/app/php/bin/php: error while loading shared libraries: libargon2.so.1: cannot open shared object file: No such file or directory
   Traceback (most recent call last):
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/scripts/compile.py", line 59, in <module>
       .from_build_pack('lib/additional_commands')
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/build_pack_utils/builder.py", line 212, in extensions
       process_extension(path, ctx, 'compile', process, args=[self])
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/build_pack_utils/utils.py", line 69, in process_extension
       success(getattr(extn, to_call)(*args))
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/extension_helpers.py", line 48, in extension_helper_wrapper
       return getattr(inst, 'compile')(install)
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/extension_helpers.py", line 154, in compile
       self._compile(install)
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/php/extension.py", line 142, in _compile
       validate_php_ini_extensions(ctx)
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/compile_helpers.py", line 168, in validate_php_ini_extensions
       all_supported =  _get_supported_php_extensions(ctx) + _get_compiled_modules(ctx)
     File "/tmp/buildpackdownloads/d4d5b8a3015550528ca809210a268b45/lib/compile_helpers.py", line 132, in _get_compiled_modules
       raise RuntimeError("Error determining PHP compiled modules")
   RuntimeError: Error determining PHP compiled modules
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
```

It is expected to find libargon2.so.1. However there's ony two files named as the following:

libargon2.so
libargon2.so.0

Is there an error in the buildpack for PHP 7.2.16?

**Comment by dmikusa-pivotal** [comment]
It's not a problem with the buildpack, but could be an issue with the binary-builder scripts. Do you have the full output of binary-builder when building PHP 7.2.16 in your environment? Also, include the full command your running to build the binary.

**Comment by crypticro** [comment]
@dmikusa-pivotal 

Today I tried to build PHP 7.1.29 using the PHP 7.1 extension file but the building failed.

Command used: docker run -w /binary-builder -v `pwd`:/binary-builder -v /oracle:/oracle -it cloudfoundry/cflinuxfs3 bash ./bin/binary-builder --name=php7 --version=7.1.29 --sha256=e03990c9a16835b4956c2dd1309ca3c84f55f8e155d5b743003880fce468e1f2  --php-extensions-file=./php-extensions.yml

Result:

`Extracting php-7.1.29.tar.gz into /tmp/x86_64-linux-gnu/ports/php7/7.1.29... OK
Running 'configure' for php7 7.1.29... OK
Running 'compile' for php7 7.1.29... OK
Running 'install' for php7 7.1.29... ERROR, review '/tmp/x86_64-linux-gnu/ports/php7/7.1.29/install.log' to see what happened. Last lines are:
========================================================================
Installing header files:          /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/include/php/
Installing helper programs:       /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin/
  program: phpize
  program: php-config
Installing man pages:             /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/php/man/man1/
  page: phpize.1
  page: php-config.1
Installing PEAR environment:      /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/lib/php/
[PEAR] Archive_Tar    - installed: 1.4.7
[PEAR] Console_Getopt - installed: 1.4.2
[PEAR] Structures_Graph- installed: 1.1.1
[PEAR] XML_Util       - installed: 1.4.3
[PEAR] PEAR           - installed: 1.10.9
Wrote PEAR system config file at: /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/etc/pear.conf
You may want to add: /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/lib/php to your php.ini include_path
/tmp/x86_64-linux-gnu/ports/php7/7.1.29/php-7.1.29/build/shtool install -c ext/phar/phar.phar /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin
ln -s -f phar.phar /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar
ln: failed to create symbolic link '/binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar': Protocol error
Makefile:508: recipe for target 'install-pharcmd' failed
make: *** [install-pharcmd] Error 1
========================================================================
bundler: failed to load command: ./bin/binary-builder.rb (./bin/binary-builder.rb)
RuntimeError: Failed to complete install task
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:398:in `block in execute'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:367:in `chdir'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:367:in `execute'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:113:in `install'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:148:in `cook'
  /binary-builder/recipe/php_meal.rb:48:in `cook'
  /binary-builder/bin/binary-builder.rb:85:in `block in <top (required)>'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:313:in `block in with_clean_env'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:562:in `with_env'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:313:in `with_clean_env'
  /binary-builder/bin/binary-builder.rb:82:in `<top (required)>'
`

**Comment by dmikusa-pivotal** [comment]
This is very odd. It doesn't seem related to actually building PHP. It's the install after that's failing, specifically this command:

```
ln -s -f phar.phar /binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar
```

The error message is:

```
ln: failed to create symbolic link '/binary-builder/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar': Protocol error
```

I think that's happening because `/binary-builder` is the Docker volume we mapped & you can't create symlinks from inside the container to the Docker mounted volume.

You could try removing "-v `pwd`:/binary-builder`" from your `docker run` command. Then build again. The downside of this is that the built files will not persist outside of your docker container, so you'd need to manually get them out somehow prior to exiting the container.

@kardolus I see that we have PHP 7.1.29 in the latest PHP buildpack. Did we see any build errors like this in the pipelines?

**Comment by crypticro** [comment]
@dmikusa-pivotal 

If I remove this I get the following:

bash: ./bin/binary-builder: No such file or directory

**Comment by dmikusa-pivotal** [comment]
Ah, sorry. Yea, that's also going to mean the binary-builder code won't be in the container. Maybe try something like this:

1.) Map the volume to a different place with 

```
-w /binary-builder-code -v `pwd`:/binary-builder-code
```

That should put the code in a different place.

2.) Then `mkdir /binary-builder` from inside the container.

I'm hoping it will run code from `/binary-builder-code` but install to `/binary-builder` which should be inside the container, not a mounted volume.

Let me know if that doesn't help, and I'll see about running some builds myself to see if I can replicate this.

**Comment by crypticro** [comment]
@dmikusa-pivotal 

I ran the following:

`docker run -w /binary-builder-code -v `pwd`:/binary-builder-code -v /oracle:/oracle -it cloudfoundry/cflinuxfs3 bash -c "mkdir /binary-builder && ./bin/binary-builder --name=php7 --version=7.1.29 --sha256=e03990c9a16835b4956c2dd1309ca3c84f55f8e155d5b743003880fce468e1f2  --php-extensions-file=./php-extensions.yml"`

but it returns the same error

Running 'install' for php7 7.1.29... ERROR, review '/tmp/x86_64-linux-gnu/ports/php7/7.1.29/install.log' to see what happened. Last lines are:
========================================================================
Installing header files:          /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/include/php/
Installing helper programs:       /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/bin/
  program: phpize
  program: php-config
Installing man pages:             /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/php/man/man1/
  page: phpize.1
  page: php-config.1
Installing PEAR environment:      /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/lib/php/
[PEAR] Archive_Tar    - already installed: 1.4.7
[PEAR] Console_Getopt - already installed: 1.4.2
[PEAR] Structures_Graph- already installed: 1.1.1
[PEAR] XML_Util       - already installed: 1.4.3
[PEAR] PEAR           - already installed: 1.10.9
Wrote PEAR system config file at: /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/etc/pear.conf
You may want to add: /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/lib/php to your php.ini include_path
/tmp/x86_64-linux-gnu/ports/php7/7.1.29/php-7.1.29/build/shtool install -c ext/phar/phar.phar /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/bin
ln -s -f phar.phar /binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar
ln: failed to create symbolic link '/binary-builder-code/ports/x86_64-linux-gnu/php7/7.1.29/bin/phar': Protocol error
Makefile:508: recipe for target 'install-pharcmd' failed
make: *** [install-pharcmd] Error 1
========================================================================
bundler: failed to load command: ./bin/binary-builder.rb (./bin/binary-builder.rb)
RuntimeError: Failed to complete install task
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:398:in `block in execute'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:367:in `chdir'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:367:in `execute'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:113:in `install'
  /var/lib/gems/2.5.0/bundler/gems/mini_portile-fddb4245149a/lib/mini_portile/mini_portile.rb:148:in `cook'
  /binary-builder-code/recipe/php_meal.rb:48:in `cook'
  /binary-builder-code/bin/binary-builder.rb:85:in `block in <top (required)>'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:313:in `block in with_clean_env'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:562:in `with_env'
  /usr/local/lib/site_ruby/2.5.0/bundler.rb:313:in `with_clean_env'
  /binary-builder-code/bin/binary-builder.rb:82:in `<top (required)>'

**Comment by dmikusa-pivotal** [comment]
OK, so I ran the exact build commands you're running just now and it worked OK for me. Here are the details of what I did.

1.) Fired up Docker 18.09.2 on my Mac 10.14.5.
2.) I ran `git clone` to get a fresh copy of binary builder.
3.) Ran `docker run -w /binary-builder -v `pwd`:/binary-builder -it cloudfoundry/cflinuxfs3 bash`. I like to start the container separate so it persists when there are problems. I also did not add the `-v` mount for `/oracle` as I do not have Oracle binaries.
4.) I downloaded [this file](https://github.com/cloudfoundry/buildpacks-ci/blob/master/tasks/build-binary-new/php7-extensions.yml).
5.) Ran `./bin/binary-builder --name=php7 --version=7.1.29 --sha256=e03990c9a16835b4956c2dd1309ca3c84f55f8e155d5b743003880fce468e1f2  --php-extensions-file=./php7-extensions.yml`.

This ran through, built and installed PHP 7.

```
Extracting php-7.1.29.tar.gz into /tmp/x86_64-linux-gnu/ports/php7/7.1.29... OK
Running 'configure' for php7 7.1.29... OK
Running 'compile' for php7 7.1.29... OK
Running 'install' for php7 7.1.29... OK
```

Can you check your system to see how it compares? Also, try without the Oracle mount. I doubt that's it, but let's rule that out. And make sure you've got the absolute latest of the master branch on binary-builder. Lastly, delete the `ports/` folder from under your binary-builder folder. This contains state that persists beyond a single build and can sometimes cause issues.

Hope that helps!

**Comment by crypticro** [comment]
@dmikusa-pivotal 

I did exactly the same but no luck here still the same error. Some information about my system:

`
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine

$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:54 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
`

**Comment by crypticro** [comment]
@dmikusa-pivotal 

I created another virtual box with Ubuntu and the script worked fine now. The binaries were greated, even with the oracle drivers.

Now facing another issue. I created a static buildpack to host the binaries but seems that cloudfoundry is unable to pull it during staging.

```
Staging app and tracing logs...
   Cell 1df62c1d-3581-4cd9-86d1-f8c504262e31 creating container for instance 1cd4c878-ccdf-45b5-a2a0-5649bd1a587d
   Cell 1df62c1d-3581-4cd9-86d1-f8c504262e31 successfully created container for instance 1cd4c878-ccdf-45b5-a2a0-5649bd1a587d
   Downloading app package...
   Downloaded app package (25.8M)
   -------> Buildpack version 4.3.77
   Installing Nginx
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/nginx-static/nginx-1.15.12-linux-x64-cflinuxfs3-4b82e605.tgz] to [/tmp]
   NGINX 1.15.12
   Installing PHP
   PHP 7.1.29
   Traceback (most recent call last):
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/scripts/compile.py", line 59, in <module>
       .from_build_pack('lib/additional_commands')
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/builder.py", line 212, in extensions
       process_extension(path, ctx, 'compile', process, args=[self])
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/utils.py", line 69, in process_extension
       success(getattr(extn, to_call)(*args))
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/extension_helpers.py", line 48, in extension_helper_wrapper
       return getattr(inst, 'compile')(install)
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/extension_helpers.py", line 154, in compile
       self._compile(install)
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/php/extension.py", line 139, in _compile
       .package('PHP')
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/builder.py", line 188, in package
       self._installer.install_binary(key)
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/cloudfoundry.py", line 214, in install_binary
       strip=strip)
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/cloudfoundry.py", line 190, in _install_binary_from_manifest
       self._dwn.download(url, self._ctx['TMPDIR'])
     File "/tmp/buildpackdownloads/310964381ce7362c3e10e21bb2b96e0a/lib/build_pack_utils/downloads.py", line 40, in download
       raise RuntimeError("Checksum of downloaded dependency does not match expected value")
   RuntimeError: Checksum of downloaded dependency does not match expected value
   Failed to compile droplet: Failed to run finalize script: exit status 1
   Exit status 223
```

**Comment by dmikusa-pivotal** [comment]
Double check the URL it's using to download PHP. It, unfortunately, is not printing the URL in the output. I think if you `cf set-env <app> BP_DEBUG=true`, the debug output should though. Anyway, see what you're getting when you download. It's possible the path is wrong and you're getting a 404 or some other non-200 status code.

The other option is that you just need to update the manifest.yml file from the PHP buildpack. In addition to placing the download URL in there, you also need to update the hash of the download. If the hash doesn't match the actual hash of the file downloaded, you'll get the error above.

**Comment by crypticro** [comment]
If I upload the binary to a storage provider such as Google (same hash) it works if I link it to a cloudfoundry static buildpack it doesn't. So my assumption is that the hash is correct but there's no connectivity from the staging environment.

**Comment by dmikusa-pivotal** [comment]
>So my assumption is that the hash is correct but there's no connectivity from the staging environment.

Yes, that could be. If you try BP_DEBUG, you might get confirmation. That will give a lot more output.

**Comment by dfreilich** [comment]
@crypticro Are you still facing issues? I'll close the issue now, but feel free to reopen, or open a new issue, if there are still problems.
