### ISSUE TITLE
Support for SSH2 extension for PHP

### ISSUE THREAD

**Issue by ericadowling** [cloudfoundry/binary-builder#48]
Hi, a PCF customer is looking to use SSH2 functions in their application with the Cloudfoundry PHP Buildpack. Is it possible to get this extension added to the PHP binaries?

This is a PECL extension and can be found here: https://pecl.php.net/package/ssh2

Thank you!

**Comment by tillyt** [comment]
Gotcha, we'll look into adding this!

**Comment by dfreilich** [comment]
@dmikusa-pivotal Do you have any objections to adding it? If not, we can get this prioritized.

**Comment by dmikusa-pivotal** [comment]
Nope. Seems like a good addition. 👍

**Comment by Zanadar** [comment]
Gonna close this as there's been no traction. @dmikusa-pivotal or whoever else, fee free to reopen if you hear otherwise.

**Comment by dmikusa-pivotal** [comment]
Yea, we should add this but time constraints are keeping me from doing it. I'll try to revisit, but no guarantees so I'm OK with closing this out for now.
