### ISSUE TITLE
Provide support for traceability to original sources

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/binary-builder#5]
Offering the ability for paas-user or paas-operator to trace back the origin of the buildpack certain helps adoption of the buildpack by teams that are used to rely on certificated distros for handling their application stack binaries.

I'm thinking for instance to archive the verbose output of the binaries, outputting md5 for downloaded sources, and md5 of resulting binaries, in order to provide traceability to original sources.

Those verbobe traces could for instande be gziped and included in the buildpack as meta-data that paas-user can consult on the app droplet (using `cf files`) or ideally in the future complete a normalized [https://docs.google.com/document/d/1y0KoHCZ5r1kCShjipnqOjcpooxPmdbaq1p9cFxi6wGA/edit#heading=h.iym9agqqf9qs](buildpack dependencies) meta-data made available to the CC, and accessible through an API to Cf users.

The https://github.com/cloudfoundry-incubator/buildpack-packager#manifest seems close to partially fullfilling this traceability goal (i.e. traeability from offlline buildpack cached dependency to remote binaries repos). I wonder whether the buildpack manifest.yml is currently available at staging or runtime to cf users ?

**Comment by flavorjones** [comment]
Hi @gberche-orange,

Thanks for bringing this subject up again. I'd love to chat more about your use case, so that I can understand a bit better what we'd need to build.

The buildpack manifest is indeed present during staging, and we even verify the checksums of any downloaded dependencies when the buildpack is operating in uncached mode.

It sounds like you're specifically asking for a way to verify a checksum on the original source tarball (or a hash on a git repository)?

**Comment by gberche-orange** [comment]
thanks @flavorjones for your response and sorry for lack of clarity/structure in this exchange.

Yes, to rephrase the need I'm expressing: Once a app has been staged through the buildpack process, how can an operator be confident that the following potential issues did not happen, or alternatively can perform forensicks to trace back to root-cause of an issue, such as

1. for a buildpack fetching online internet dependencies (say the S3 bucket pivotal is exposing):
  1. the S3 bucket can compromised, and someone injected trojans
  2. the CF/pivotal pipelines were compromised and injected trojans into the S3 buckets 
  3. the source repo DNS were temporary hijacked and infected sources were served from an attacker repo
  4. the source repos (or one of its replica) were compromised and trojans were injected into source code
2. for a buildpack fetching dependencies replicated on-prem:
   1. the replica was corrupted and is serving infected binaries

So I'm suggesting to record the evidences of successive steps in the process, so that someone can have elements to trace back and identify potential issues.

So, I'm suggesting an operator could inspect a staged app. By downloading one available log file, the operator could trace back manually up to the original source tarball URL and MD5/SHA, and most important steps in the chains.

In https://github.com/cloudfoundry/binary-builder/issues/4 I was suggesting to prevent 1iii and 1iv

To prevent 1i and 2i, it would be good to have binaries provided by CF/Pivotal be digitally signed, and publish a CF/Pivotal public key to verify them. Ideally, embed the public key at staging time so the signatures can be checked at staging time.

**Comment by flavorjones** [comment]
I've created a track of work around this request, which is outlined here:

> https://docs.google.com/document/d/1vKHD0ulIq3Vw3J6-wI7AZ3peu2ZnPdXLYh0F1Rl-w8s/edit#

and the Tracker epic is here:

> https://www.pivotaltracker.com/epic/show/2077742

**Comment by jvshahid** [comment]
It has been a while since the issue was opened and lot has changed since then. I think we currently address `1i` and `2i` by hashing the downloaded artifacts and making sure the hash matches the value found in the manifest. `1iii` & `1iv` are also covered by the pipeline checking the downloaded asset hash, and if available the gpg signature of the downloaded asset. This leave `1ii` which I'm not sure how to tackle. thoughts ?

**Comment by jvshahid** [comment]
bump

**Comment by gberche-orange** [comment]
Sorry for late response on this. Thanks for the great improvements brought as part of this "chain of custody" epic!

One possibility for ``1ii the CF/pivotal pipelines were compromised and injected trojans into the S3 buckets`` could be to publish the Cf/pivotal pipeline outputs including intermediate checksums for inputs (any download, concourse docker resource...) and outputs, so that a independent party is able to scrutinize it, reproduce it and detect from suspicious deltas. This may require to sanitize the public CI so that logs get made publicly available without leaking secrets.

For a 3rd party to be able to detect intrusions, this may require behavior close to [reproductible builds](https://wiki.debian.org/ReproducibleBuilds) in the buildpacks CI, i.e. tracking and removing non reproductible parts (such as timestamps).

**Comment by RochesterinNYC** [comment]
I believe that the work in this story is related to your issue @gberche-orange: https://www.pivotaltracker.com/story/show/120319485

This story is essentially focused on making our Concourse logs public.

When you refer to "intermediate checksums for inputs and outputs" in regards to the pipeline, are you referring to specific Concourse resources used in tasks in the pipelines?

**Comment by RochesterinNYC** [comment]
@gberche-orange Still looking for some clarification on your comments regarding "intermediate checksums for inputs and outputs". Thanks.

**Comment by gberche-orange** [comment]
Sorry @RochesterinNYC for the late response on this (it took time us to set up our instance of buildpacks-ci in order to try to provide relevant comments).

/CC @o-orand

Having concourse logs public as described in https://www.pivotaltracker.com/story/show/120319485 indeed contributes to providing ways for the community to have more visibility and be more protected against ```1ii the CF/pivotal pipelines were compromised and injected trojans into the S3 buckets```. It's great to see progresses being made on this story, and the https://github.com/cloudfoundry/docs-buildpacks/pull/71 to ease understanding buildpack ci.

> Still looking for some clarification on your comments regarding "intermediate checksums for inputs and outputs".

I was thinking that if some more fingerprints were added into the buildpack-ci output logs, it would be easier for an independent party to scrutinize them and potentially identify a compromise, or instead feel confident that the pipeline is safe and hard to break into.

Taking a specific example of the httpd binary building with the following output in our pipeline (likely to correspond to https://buildpacks.ci.cf-app.com/pipelines/binary-builder/jobs/build-httpd/builds/1)

![annotated-concourseci-screenshot](https://cloud.githubusercontent.com/assets/4748380/16683322/8c475294-44ff-11e6-88ac-97f2c9a418a7.png)

This would mean adding MD5 at the end of the steps 

````
Downloading apr-1.5.2.tar.gz (100%)
Extracting apr-1.5.2.tar.gz into /tmp/x86_64-linux-gnu/ports/apr/1.5.2... OK
Running 'configure' for apr 1.5.2... OK
Running 'compile' for apr 1.5.2... OK
Running 'install' for apr 1.5.2... OK
Downloading apr-iconv-1.2.1.tar.gz (100%)
Extracting apr-iconv-1.2.1.tar.gz into /tmp/x86_64-linux-gnu/ports/apr-iconv/1.2.1... OK
Running 'configure' for apr-iconv 1.2.1... OK
Running 'compile' for apr-iconv 1.2.1... OK

TODO: display APR hash here

Extracting httpd-2.4.20.tar.bz2 into /tmp/x86_64-linux-gnu/ports/httpd/2.4.20... OK
Running 'configure' for httpd 2.4.20... OK
Running 'compile' for httpd 2.4.20... OK
Running 'install' for httpd 2.4.20... OK
Running 'archive' for httpd 2.4.20... OK

TODO: display httpd archive hash here
```

I tried the exercise of:
- 1) printing the traceability chain for httpd of 2.4.20 which is the [current version](https://github.com/cloudfoundry/php-buildpack/blob/a049e82ffc56f5bbc8059831328b59589e8d854d/manifest.yml#L32-L35) used in the buildpack, with the corresponding [story](https://www.pivotaltracker.com/story/show/116903551)  and try to follow the [documented chain of custody](https://docs.google.com/document/d/1vKHD0ulIq3Vw3J6-wI7AZ3peu2ZnPdXLYh0F1Rl-w8s/edit#)
2) evaluating the reproductibility of builds: i.e. is it possible for a 3rd party to reliably reproduce the binary builds from available data.

Binary traceability chain:
- sources hash (``md5: 3ff4f00ee051cf5d5304b47b1bc418b8`` corresponding to https://archive.apache.org/dist/httpd/httpd-2.4.20.tar.bz2 URL built in the [binary-builder httpd recipe](https://github.com/cloudfoundry/binary-builder/blob/73c9440b9674f31975a4b7eef06ccb54d025f3cd/recipe/httpd_meal.rb#L61-L61)) are recorded into https://github.com/cloudfoundry/buildpacks-ci/commit/cee826dc978f013840ef6a8193ec6ee75536778b (not cross-linked with the story in this case)
- source-to-binary logs are into https://buildpacks.ci.cf-app.com/pipelines/binary-builder/jobs/build-httpd/builds/80 (the URL is currently broken. Is it due to a concourse update/redeploy ?). Our local ci instance displays the following traces
```
  Source YAML:
---
- url: https://archive.apache.org/dist/httpd/httpd-2.4.20.tar.bz2
  sha256: 0e76a375ed3dbac636f50ac39de966ece443751fe4d62392f9a360a19d94d0da
```
   - with httpd binary hash (``binary-builder/httpd-2.4.20-linux-x64.tgz, md5: 22dcae98467c318a856589d171670a01`` )  recorded as a buildpacks-ci repo [git commit log](https://github.com/cloudfoundry/buildpacks-ci/commit/c44c66476d10d6b4a983e7f62181690053a03527)
- httpd binary hash (``md5: 22dcae98467c318a856589d171670a01 ``) are added into [php-buildpack/manifest.yml commit](https://github.com/cloudfoundry/php-buildpack/commit/40e6661555181b6fbd19f3c1839e3473baff7b78#diff-8f7df7fa0d4d3156b5cf623a87156eceL41) (lacking traceability with the story)
- AWS binary are at https://pivotal-buildpacks.s3.amazonaws.com/concourse-binaries/httpd/httpd-2.4.20-linux-x64.tgz with expected content matching the md5 hash


Versionning of the CI used to produced the binary, from a given build output referenced in the story:
- concourse output logs display the buidpacks-ci git hash (see [screenshot197](https://cloud.githubusercontent.com/assets/4748380/16684732/f0f55478-4506-11e6-8585-2891a1db7b8b.png) so 
   - with [docker image resources hashes](https://github.com/cloudfoundry/buildpacks-ci/blob/d2b62c166ed9e1121570a2a98eb526e15fc55aab/tasks/binary-builder.yml#L2-L2): 
      - currently pointing to docker hub head, so it is hard to precisely know which version was used
      - docker resources pull traces in concourse logs are not archived within the builds
   - with concourse version number used: 1.2
      - concourse version is only displayed on the homepage but not archived in logs, so could have changed)

I'll try formalizing improvement suggestions soon as a result of this. I also vonlunteered to the buildpack interview next week, if ever this could be an opportunity to further exchange on this topic.

Thanks again for the great improvement work on buildpacks audit trace,

Guillaume & Olivier.

**Comment by gberche-orange** [comment]
Improvement suggestions on the traceability of source to binary:
* make it easier to navigate from pivotal tracker story to invidivual commits and hashes of source and binaries:
   * manually pushed commits to include the tracker reference
   * automatically pushed commit such as https://github.com/cloudfoundry/buildpacks-ci/commit/c44c66476d10d6b4a983e7f62181690053a03527 to include tracker reference
* archive build logs associated to released artifacts (e.g. on S3 along with binaries) to ensure logs are available independently of buildpack-ci instance refactoring (similarly to a long term archival of ubuntu packages such as [php 5.5](https://launchpad.net/~ondrej/+archive/ubuntu/php5) its [list of builds](https://launchpad.net/~ondrej/+archive/ubuntu/php5/+builds?build_state=built) and individual [build archive](https://launchpadlibrarian.net/256720822/buildlog_ubuntu-trusty-armhf.nghttp2_1.10.0-1+deb.sury.org~trusty+1_BUILDING.txt.gz))
* make it easier for the community to reproduce the buildpack-ci, in whole or in parts, and in particular and independently verify the source to binary process (likely to depend on [reproductible builds](https://wiki.debian.org/ReproducibleBuilds) on prem:
   * record in the archived log the environment details: the concourse ci version used, the tasks' docker images hash. This may be potentially be a concourse improvement that could apply to other teams ci.
   * parametrize the buildpack-ci repo so that independent parties are able to run them

**Comment by geramirez** [comment]
@gberche-orange thanks for the feedback and improvements suggestions. I've added a [story](https://www.pivotaltracker.com/story/show/126066319) for us to review comments more closely.

**Comment by jchesterpivotal** [comment]
It turns out (unsurprisingly) that we're not the first to grapple with this.

See this [long discussion](https://github.com/rust-lang/crates.io/issues/75) by the Cargo team, including references to one design in the wild -- TUF ("The Update Framework") and Toto, which was apparently renamed [Diplomat](https://www.usenix.org/conference/nsdi16/technical-sessions/presentation/kuppusamy).

Of note, Steve Klabnik is a friend of Labs and lives in Brooklyn. The authors of the Diplomat paper are at NYU.

**Comment by keaty** [comment]
@gberche-orange we've made a lot of changes over the past year that address a lot of the original issues that you brought up in regards to traceability and auditing, ex:
- [public CI builds](http://concourse-summary-crucial-tasimeter.cfapps.io/host/concourse.buildpacks-gcp.ci.cf-app.com)
- [tracker story IDs in automated commits](https://github.com/cloudfoundry/php-buildpack/commit/c4addf71c4a433e2338187a6b9a92a1c48d6b061)
- [build history for automated builds](https://github.com/cloudfoundry/public-buildpacks-ci-robots/blob/master/binary-built-output/glide-built.yml)
- [Non hard-coded parameterization for a lot of our CI configuration](https://github.com/cloudfoundry/buildpacks-ci/blob/master/public-config.yml) ([courtesy of @o-orand](https://github.com/cloudfoundry/buildpacks-ci/commits/master?author=o-orand))

What other concerns or missing functionalities are there in terms of traceability and auditing?

**Comment by gberche-orange** [comment]
thanks @keaty for the update and for this great work! I'll try to review the pointers above shortly and provide more feedback

**Comment by sesmith177** [comment]
@gberche-orange Have you had a chance to take a look at this recently?

**Comment by dgodd** [comment]
@gberche-orange Have you had a chance to take a look at this recently?

**Comment by gberche-orange** [comment]
@dgodd @sesmith177 @keaty apologies for the delay in responding to this issue. 

Thanks for the additional comments in https://www.pivotaltracker.com/n/projects/1042066/stories/126066319 which I reproduce below for easier reading in this issue


> ##Traceable history of builds and shas/md5s of sources and artifacts that do not only live in Concourse logs.
> Concourse logs can easily be lost and past deployment logs (not part of current deployed Concourse database) are also not really viewable. All build history/verification should be in publicly viewable places like so: https://github.com/cloudfoundry/public-buildpacks-ci-robots/blob/master/binary-built-output/composer-built.yml
> 
> ##Ability to see Concourse version, docker image sha, etc. for a build
> If we have two sequential builds that are running the same get resource versions, but one is failing and the other is passing, things like Concourse version, Garden version, docker image version (cfbuildpacks/ci) can be the reason. However, we have no visibility into the versions of things used for a build.

Could the version for dependencies (e.g. concourse version, docker image hash, etc) be recorded in archived build verification such as [binary-built-output](https://github.com/cloudfoundry/public-buildpacks-ci-robots/tree/master/binary-built-output). Could the concourse team help with exporting meta-data for buildpacks-ci to consume?

Related to PHP binary building and traceability, I'd like a confirmation in https://concourse.buildpacks-gcp.ci.cf-app.com/teams/main/pipelines/binary-builder/jobs/build-php/builds/2 that the displayed sha256 don't match because in the builds-out job, the displayed sha256 is a tar.gz while in the _build_binary it is the plain binary file ? 

![screenshot507](https://cloud.githubusercontent.com/assets/4748380/22042494/c77e3eaa-dd0b-11e6-8957-f54c5e337122.png)

Besides, https://github.com/cloudfoundry/binary-builder/blob/a5db8e4d14db7ae6ab55eb0295c1a11c778af93d/recipe/php_common.rb#L373-L386 seems to have regressed w.r.t. https://github.com/cloudfoundry/binary-builder/issues/4#issuecomment-119778263 and be pulling many dependencies off HTTP connections without checking hashes, being vulnerable to MITM attacks such as DNS spoofing.

Thanks again for the great improvements brought to traceability, this makes the CF a much safer platform !

**Comment by sclevine** [comment]
Story created to fix the Cassandra deps: https://www.pivotaltracker.com/story/show/137890189

**Comment by gberche-orange** [comment]
thanks @sclevine It seems to me this story needs to be expanded to the PeclRecipe based recipes that do not seem to have their hash verified either 
https://github.com/cloudfoundry/binary-builder/blob/a5db8e4d14db7ae6ab55eb0295c1a11c778af93d/recipe/php_common.rb#L51
https://github.com/cloudfoundry/binary-builder/blob/a5db8e4d14db7ae6ab55eb0295c1a11c778af93d/recipe/php_common.rb#L80
https://github.com/cloudfoundry/binary-builder/blob/a5db8e4d14db7ae6ab55eb0295c1a11c778af93d/recipe/php_common.rb#L99


Some other PeclRecipe based recipes use https to download binaries, reducing risk of MITM, may benefit from hash checking (as to protect against remote repository compromise)
https://github.com/cloudfoundry/binary-builder/blob/a5db8e4d14db7ae6ab55eb0295c1a11c778af93d/recipe/php_common.rb#L143

BTW, I wonder whether the buildpacks team considered producing a blog to publicize the great work done on the binary building traceability and audeability, similar to other security-related blogs such as https://medium.com/built-to-adapt/the-three-r-s-of-enterprise-security-rotate-repave-and-repair-f64f6d6ba29d ? It would be great to explain rationales for building from source and leverage distro-provided binaries, and explain the sophisticated, robust buildpack CI to produce timely secured binaries to rootfs and buildpacks. 

Searching in the backlog for [blog related stories](https://www.pivotaltracker.com/n/projects/1042066/search?q=blog%20), this one did not seem to be brought up yet.

**Comment by sesmith177** [comment]
@gberche-orange All the PeclRecipe based recipes should verify the hashes of the downloaded files as they inherit from MiniPortile which does so (https://github.com/cf-buildpacks-eng/mini_portile/blob/master/lib/mini_portile/mini_portile.rb#L53) .  The md5s are specified in the calls to standard_pecl in the php recipes

With regard to the different hashes in concourse logs, which two are you referring to? 0b1b... is the sha of the php source code and 0572... is the sha of the output .tgz file

Let me know if this helps

**Comment by gberche-orange** [comment]
> All the PeclRecipe based recipes should verify the hashes of the downloaded files as they inherit from MiniPortile which does so (https://github.com/cf-buildpacks-eng/mini_portile/blob/master/lib/mini_portile/mini_portile.rb#L53) . The md5s are specified in the calls to standard_pecl in the php recipes

my mistake sorry, thanks @sesmith177 

> With regard to the different hashes in concourse logs, which two are you referring to? 0b1b... is the sha of the php source code and 0572... is the sha of the output .tgz file

Thanks for the clarification.

**Comment by gberche-orange** [comment]
Interesting, as this echoes the current industry wide effort around `Supply chain Levels for Software Artifacts, or SLSA (salsa)`
https://slsa.dev/
https://slsa.dev/spec/v0.1/levels#summary-of-levels
