### ISSUE TITLE
Custom Module Load in HTTPD

### ISSUE THREAD

**Issue by mkkeffeler** [cloudfoundry/binary-builder#51]
We are trying to load a custom module in HTTPD that isn't already installed. We have a PHP app using the php buildpack that needs to load a custom module. What is the best way to get it installed so we can use that custom module in httpd?

**Comment by dmikusa-pivotal** [comment]
The binary-builder can help you build the module. Take a look at the HTTP meal for details on how we build HTTPD. 

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/httpd_meal.rb

In particular, see the parts for how we configure mod_openidc which is a third party module that is included.

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/httpd_meal.rb#L95-L107

and

https://github.com/cloudfoundry/binary-builder/blob/master/recipe/httpd_meal.rb#L188-L193

Hope that helps!

**Comment by chhhavi** [comment]
Are you still facing issues @mkkeffeler? I'm closing this issue for now, if you continue to face issues, please feel free to open the issue again.
