### ISSUE TITLE
Add back support for solr php extension with PHP v7.2 and above

### ISSUE THREAD

**Issue by devtdeng** [cloudfoundry/binary-builder#52]
**Buildpack:** 
PHP Buildpack

**Request:** 
Solr extension has been removed from PHP buildpack (with PHP v7.2 and above) because there were no compatible Solr releases.

On 2019-07-04, Solr v2.5.0 was released with PHP v7.1~7.4 compatibility. Can Solr be added back to PHP buildpack extensions when using PHP 7.2 and above?
https://pecl.php.net/package-changelog.php?package=solr&release=2.5.0

**Comment by Zanadar** [comment]
We've add this extension in for `php 7.2+ ` (bonus point the manifest now shows extension versions when they're available)
https://github.com/cloudfoundry/php-buildpack/commit/c7b12e4e9ba494fe937a794cb5e856a4a35cee4f
