### ISSUE TITLE
Shebangs for bundler executables should be for a generalized ruby

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/binary-builder#54]
The ruby-buildpack consumes bundler as a dependency. The bundler tarball provided by the recipe in the repo includes the bundle gem source code and a couple of executables in the `bin/` directory that allow bundler to be executed from the command line.

When I print out the contents of one of the executables, I see the following:
```sh
#!/usr/bin/env ruby2.5
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end
```

This looks pretty reasonable with the exception of the shebang on the very first line. That line is looking for an executable on the `$PATH` called `ruby2.5`. Unfortunately, the ruby-buildpack installed different versions of ruby and so is not guaranteed to have a `ruby2.5` executable on the `$PATH`.

To patch around this, the ruby-buildpack includes [some code](https://github.com/cloudfoundry/ruby-buildpack/blob/59d6b1984dba17cf4bad5933e608d528b63ae461/src/ruby/supply/supply.go#L416-L451) that rewrites these shebangs so that they can be executed within the context of the droplet with whichever version of ruby is installed.

We'd like to remove this code and thus simplify the buildpack codebase, but to do so, we'd need the shebangs to point to a generic `ruby`. Would it be possible for this to happen?

**Comment by mdelillo** [comment]
Fixed in [this commit](https://github.com/cloudfoundry/binary-builder/commit/eb3c2b8dee5d1943bca44b67028c97c12a864869)
