### ISSUE TITLE
Add support for solr php extension

### ISSUE THREAD

**Issue by ayanozturk** [cloudfoundry/binary-builder#9]
Hi,

Solr (http://lucene.apache.org/solr/) is open source search platform built on Apache Lucene. We are using it for our indexing and search requirements and currently we have to fork main php-buildpack repository to be able to use this extension in CF containers.

solr extension can be installed using pecl: https://pecl.php.net/package/solr also mentioned in php.net documentation: http://php.net/manual/en/solr.installation.php

**Comment by RochesterinNYC** [comment]
Closed by #10
